# Generated by Django 4.1 on 2022-09-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('precio', models.BigIntegerField()),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.IntegerField()),
                ('categoria', models.ManyToManyField(to='products.categoria')),
                ('talla', models.ManyToManyField(to='products.talla')),
            ],
        ),
    ]
